/**
 * Self-hosted first-party tracker source. It has no remote dependency, no
 * form/input capture, no fingerprinting, and no open-pixel behavior.
 * [COMP:api/campaign-tracking]
 */
export const CAMPAIGN_TRACKER_SOURCE = String.raw`(()=>{
"use strict";
const VERSION=1,KEY="brian_campaign_v1",SESSION_MS=30*60*1000,MAX_AGE=30*24*60*60;
let config=null,enabled=false,memory=null,lastPath=null;
const id=()=>{const bytes=new Uint8Array(18);crypto.getRandomValues(bytes);return btoa(String.fromCharCode(...bytes)).replaceAll("+","-").replaceAll("/","_").replaceAll("=","")};
const safePath=(path)=>path.split("/").map((part,index)=>index===0?"":(/^[0-9a-f-]{16,}$/i.test(part)||/@/.test(part)||/^\d+$/.test(part)?":id":part.slice(0,80))).join("/").slice(0,500)||"/";
const readCookie=()=>{const hit=document.cookie.split(";").map(v=>v.trim()).find(v=>v.startsWith(KEY+"="));if(!hit)return null;try{return JSON.parse(decodeURIComponent(hit.slice(KEY.length+1)))}catch{return null}};
const writeCookie=(value)=>{if(!config||config.storageMode!=="first_party"||!config.storageAllowed)return;const domain=config.cookieDomain?"; Domain="+config.cookieDomain:"";document.cookie=KEY+"="+encodeURIComponent(JSON.stringify(value))+"; Path=/; Max-Age="+MAX_AGE+"; SameSite=Lax"+domain};
const clearCookie=()=>{const domain=config&&config.cookieDomain?"; Domain="+config.cookieDomain:"";document.cookie=KEY+"=; Path=/; Max-Age=0; SameSite=Lax"+domain};
const query=()=>{const p=new URLSearchParams(location.search),utm={};for(const [wire,key] of [["utm_source","source"],["utm_medium","medium"],["utm_campaign","campaign"],["utm_content","content"],["utm_term","term"]]){const value=p.get(wire);if(value)utm[key]=value.slice(0,200)}return{linkId:p.get("brian_link")||undefined,utm:Object.keys(utm).length?utm:undefined}};
const context=()=>{const now=Date.now(),incoming=query(),stored=(config&&config.storageMode==="first_party"&&config.storageAllowed?readCookie():memory)||{},visitorId=stored.visitorId||id(),sessionId=(!stored.sessionAt||now-stored.sessionAt>SESSION_MS)?id():(stored.sessionId||id()),next={visitorId,sessionId,sessionAt:now,linkId:incoming.linkId||stored.linkId,utm:incoming.linkId||incoming.utm?incoming.utm:stored.utm};memory=next;writeCookie(next);return next};
const send=async(type,metadata={})=>{if(!enabled||!config)return false;const state=context(),body={version:VERSION,eventId:id(),siteId:config.siteId,type,occurredAt:new Date().toISOString(),linkId:state.linkId,sessionId:state.sessionId,visitorId:state.visitorId,pagePath:safePath(location.pathname),referrerOrigin:document.referrer?new URL(document.referrer).origin:undefined,utm:state.utm,test:Boolean(config.test),metadata};const payload=JSON.stringify(body);try{if(navigator.sendBeacon&&navigator.sendBeacon(config.collectUrl,new Blob([payload],{type:"application/json"})))return true;return (await fetch(config.collectUrl,{method:"POST",headers:{"content-type":"application/json"},body:payload,keepalive:true,credentials:"omit"})).ok}catch{return false}};
const page=()=>{const path=location.pathname+location.search;if(path===lastPath)return;lastPath=path;void send("page_view")};
const api={init(options){config={storageMode:"none",storageAllowed:false,...options};if(config.collectUrl&&config.siteId){const u=new URL(config.collectUrl,location.href);u.searchParams.set("site_id",config.siteId);config.collectUrl=u.toString()}enabled=Boolean(options&&options.enabled);if(!enabled)return api;context();page();addEventListener("popstate",page);const push=history.pushState;history.pushState=function(...args){push.apply(this,args);queueMicrotask(page)};const replace=history.replaceState;history.replaceState=function(...args){replace.apply(this,args);queueMicrotask(page)};return api},enable(options={}){if(!config)throw new Error("BrianCampaign.init is required");config={...config,...options};enabled=true;context();page();return api},disable(){enabled=false;memory=null;clearCookie();return api},track(type,metadata={}){if(!["page_view","cta_clicked","form_started","conversion_hint"].includes(type))throw new Error("Unsupported campaign event");return send(type,metadata)},context(){if(!config||!enabled)return null;const value=context();return{version:VERSION,siteId:config.siteId,linkId:value.linkId,sessionId:value.sessionId,utm:value.utm}}};
Object.defineProperty(window,"BrianCampaign",{value:api,writable:false,configurable:false});
})();`
