/** Compatibility re-exports; canonical schemas live in core/association. */
export {
  AssociationActorSchema,
  type AssociationActor,
  AssociationExternalIdentityInputSchema as ExternalIdentityInputSchema,
  type AssociationExternalIdentityInput as ExternalIdentityInput,
  AssociationEnquiryCreateSchema as EnquiryCreateSchema,
  type AssociationEnquiryCreateInput as EnquiryCreateInput,
  AssociationEnquiryStatusSchema as EnquiryStatusSchema,
  type AssociationEnquiryStatus as EnquiryStatus,
  AssociationEnquiryUpdateSchema as EnquiryUpdateSchema,
  type AssociationEnquiryUpdateInput as EnquiryUpdateInput,
  AssociationEnquiryNoteInputSchema as EnquiryNoteInputSchema,
  type AssociationEnquiryNoteInput as EnquiryNoteInput,
  AssociationConsentInputSchema as ConsentInputSchema,
  type AssociationConsentInput as ConsentInput,
  AssociationPlanInputSchema as PlanInputSchema,
  type AssociationPlanInput as PlanInput,
  AssociationMembershipInputSchema as MembershipInputSchema,
  type AssociationMembershipInput as MembershipInput,
  AssociationMembershipUpdateSchema as MembershipUpdateSchema,
  type AssociationMembershipUpdateInput as MembershipUpdateInput,
  AssociationMembershipRescueStatusSchema as MembershipRescueStatusSchema,
  type AssociationMembershipRescueStatus as MembershipRescueStatus,
  AssociationMembershipRescueCreateSchema as MembershipRescueCreateSchema,
  type AssociationMembershipRescueCreateInput as MembershipRescueCreateInput,
  AssociationMembershipRescueSettlementSchema as MembershipRescueSettlementSchema,
  type AssociationMembershipRescueSettlementInput as MembershipRescueSettlementInput,
  AssociationMembershipRescueReversalSchema as MembershipRescueReversalSchema,
  type AssociationMembershipRescueReversalInput as MembershipRescueReversalInput,
  AssociationMembershipRescueCancellationSchema as MembershipRescueCancellationSchema,
  type AssociationMembershipRescueCancellationInput as MembershipRescueCancellationInput,
  AssociationEventInputSchema as EventInputSchema,
  type AssociationEventInput as EventInput,
  AssociationTicketInputSchema as TicketInputSchema,
  type AssociationTicketInput as TicketInput,
  AssociationPromotionInputSchema as PromotionInputSchema,
  type AssociationPromotionInput as PromotionInput,
  AssociationPromotionImportSchema as PromotionImportSchema,
  type AssociationPromotionImportInput as PromotionImportInput,
  AssociationOrderAttendeeSchema as OrderAttendeeSchema,
  AssociationOrderLineInputSchema as OrderLineInputSchema,
  AssociationOrderCreateSchema as OrderCreateSchema,
  type AssociationOrderCreateInput as OrderCreateInput,
  AssociationSourceOrderImportSchema as SourceOrderImportSchema,
  type AssociationSourceOrderImportInput as SourceOrderImportInput,
  AssociationOrderStatusSchema as OrderStatusSchema,
  type AssociationOrderStatus as OrderStatus,
  AssociationOrderFinancialSummarySchema as OrderFinancialSummarySchema,
  type AssociationOrderFinancialSummary,
  AssociationProviderEventInputSchema as ProviderEventInputSchema,
  type AssociationProviderEventInput as ProviderEventInput,
  AssociationProviderFinancialEventInputSchema as ProviderFinancialEventInputSchema,
  type AssociationProviderFinancialEventInput as ProviderFinancialEventInput,
  AssociationRegistrationStatusSchema as RegistrationStatusSchema,
  type AssociationRegistrationStatus as RegistrationStatus,
  AssociationOperationalRosterRowSchema as OperationalRosterRowSchema,
  type AssociationOperationalRosterRow,
  AssociationRegistrationUpdateSchema as RegistrationUpdateSchema,
  type AssociationRegistrationUpdateInput as RegistrationUpdateInput,
  AssociationCheckInCorrectionSchema as CheckInCorrectionSchema,
  type AssociationCheckInCorrectionInput as CheckInCorrectionInput,
  AssociationListPageSchema as ListPageSchema,
  associationFingerprint,
  mayTransitionAssociationOrder as mayTransitionOrder,
  mayTransitionAssociationRegistration as mayTransitionRegistration,
  type AssociationErrorCode,
  AssociationError,
} from '@use-brian/core'
