// @vitest-environment jsdom
import { act,type ReactNode } from "react";
import { createRoot,type Root } from "react-dom/client";
import { beforeEach,afterEach,describe,it,expect,vi } from "vitest";
const api=vi.hoisted(()=>({module:vi.fn(),list:vi.fn(),plan:vi.fn(),event:vi.fn(),ticket:vi.fn(),promotion:vi.fn(),reserve:vi.fn(),offer:vi.fn(),checkIn:vi.fn(),correctCheckIn:vi.fn(),retryReceipt:vi.fn(),createRescue:vi.fn(),settleRescue:vi.fn(),reverseRescue:vi.fn(),cancelRescue:vi.fn(),grant:vi.fn(),adjust:vi.fn(),lookup:vi.fn(),confirm:vi.fn(),purposes:vi.fn(),download:vi.fn(),roster:vi.fn()}));
vi.mock("@/lib/api/association",async original=>({...await original<typeof import("@/lib/api/association")>(),getAssociationModuleSnapshot:api.module,listAssociationPage:api.list,saveAssociationPlan:api.plan,saveAssociationEvent:api.event,saveAssociationTicket:api.ticket,saveAssociationPromotion:api.promotion,reserveAssociationOrder:api.reserve,offerAssociationPlace:api.offer,checkInAssociationAttendee:api.checkIn,correctAssociationCheckIn:api.correctCheckIn,retryAssociationProviderReceipt:api.retryReceipt,createAssociationMembershipRescue:api.createRescue,settleAssociationMembershipRescue:api.settleRescue,reverseAssociationMembershipRescue:api.reverseRescue,cancelAssociationMembershipRescue:api.cancelRescue,exportAssociationAttendees:api.download,exportAssociationOperationalRoster:api.roster}));
vi.mock("@/lib/api/crm",()=>({grantCrmEntitlement:api.grant,updateCrmEntitlement:api.adjust,fetchCrmLookup:api.lookup,listCrmConsentPurposes:api.purposes}));
vi.mock("@/lib/surface-prefetch",()=>({associationModuleCacheKey:(w:string)=>`association-module:${w}:viewer`,associationPageCacheKey:(w:string,r:string,q={})=>`crm:${w}:viewer:${r}:${JSON.stringify(q)}`,associationIntentKey:(w:string,op:string,target:string)=>`request:${w}:viewer:${op}:${target}`}));
vi.mock("@/components/ui/confirm-dialog",()=>({confirmDialog:api.confirm}));
import { I18nProvider } from "@/lib/i18n/client";
import { en } from "@/lib/i18n/dictionaries/en";
import { AssociationPlanForm,AssociationEventForm,AssociationTicketForm,AssociationPromotionForm } from "../catalog-forms";
import { AssociationMembershipForm,AssociationMembershipsPanel } from "../memberships-panel";
import { AssociationMembershipRescueActionForm,AssociationMembershipRescueForm } from "../membership-rescue";
import { AssociationReservationForm } from "../reservation-form";
import { AssociationWaitlistOffer,AssociationWaitlistPanel } from "../waitlist-panel";
import { AssociationEventsPanel } from "../events-panel";
import { AssociationOperationsPanel } from "../operations-panel";
import { useAssociationPage,AssociationListState } from "../operator-controls";
import { resetSurfaceCache,markSurfaceCacheStale } from "@/lib/surface-cache";
import type { AssociationPlan,AssociationTicket,AssociationEvent,AssociationPromotion,AssociationMembership,AssociationMembershipRescue,AssociationWaitlistRow } from "@/lib/api/association";
(globalThis as {IS_REACT_ACT_ENVIRONMENT?:boolean}).IS_REACT_ACT_ENVIRONMENT=true;
const t=en.associationPage,m=t.manage;
const contact={id:"contact-one",name:"Fictional Person",hint:"person@example.com"};
const plan:AssociationPlan={id:"plan-one",planKey:"community",name:"Community",currency:"USD",feeMinor:"0",billingPeriod:"manual",benefits:["Workshops"],eligibilityNote:"Open to adults",published:true,activeFrom:"2027-01-01T00:00:12.345Z",activeTo:null,provider:null,providerPlanId:null};
const paidPlan:AssociationPlan={...plan,id:"plan-paid",planKey:"paid",name:"Paid community",feeMinor:"10000",billingPeriod:"annual"};
const ticket:AssociationTicket={id:"ticket-one",key:"standard",name:"Standard",currency:"USD",priceMinor:"0",memberPriceMinor:null,eligiblePlanKeys:[],eligibilityRequired:false,eligibilityScope:"buyer",capacity:12,available:10,reservedCount:2,perOrderLimit:3,saleStartsAt:null,saleEndsAt:null,status:"on_sale"};
const event:AssociationEvent={id:"event-one",slug:"workshop",title:"Workshop",description:"Description",startsAt:"2027-01-05T12:00:00Z",endsAt:"2027-01-05T15:00:00Z",timezone:"Europe/Paris",mode:"venue",venue:"Community hall",onlineUrl:null,registrationOpensAt:null,registrationClosesAt:null,capacity:20,status:"published",canonicalUrl:"https://example.com/workshop",programmeKey:"community",metadata:{format:"workshop"}};
const promotion:AssociationPromotion={id:"promotion-one",key:"launch",name:"Launch offer",discountType:"percentage",percentageBasisPoints:1500,buyQuantity:null,getQuantity:null,targetKind:"event",targetIds:[event.id],validFrom:"2027-01-01T00:00:00Z",validTo:null,maxUses:100,maxUsesPerContact:1,combinesWithMemberPrice:false,releaseOnFullRefund:false,status:"active",hasCode:true,reservedUses:2,redeemedUses:4,createdAt:"2026-01-01",updatedAt:"2026-01-01"};
const membership:AssociationMembership={id:"membership-one",contactId:contact.id,contactName:contact.name,planId:plan.id,planKey:plan.planKey,planName:plan.name,status:"active",isEffective:false,effectiveAt:"2026-09-09T00:00:00Z",startsAt:"2027-01-01T00:00:00Z",endsAt:null,renewalMode:"none",provider:null,providerEntitlementId:null,createdAt:"2026-01-01",updatedAt:"2026-01-01"};
const waitlist:AssociationWaitlistRow={id:"submission-one",contactId:contact.id,contactName:contact.name,eventId:event.id,ticketId:ticket.id,waitlistState:"waiting",promotionId:null,orderId:null,reservationExpiresAt:null};
const rescue:AssociationMembershipRescue={id:"rescue-one",contactId:contact.id,contactName:contact.name,planId:paidPlan.id,planKey:paidPlan.planKey,planName:paidPlan.name,status:"outstanding",amountMinor:"10000",currency:"USD",startsAt:"2027-01-01T00:00:00Z",endsAt:"2028-01-01T00:00:00Z",dueAt:"2026-12-01T00:00:00Z",reason:"Reviewed exception",overdue:false,membershipId:null,membershipStatus:null,settlementMethod:null,settlementReference:null,settlementOccurredAt:null,settlementNote:null,reversalReference:null,reversalOccurredAt:null,reversalReason:null,cancellationReason:null,createdAt:"2026-09-01T00:00:00Z",updatedAt:"2026-09-01T00:00:00Z"};
let host:HTMLDivElement,root:Root;
async function render(children:ReactNode){await act(async()=>root.render(<I18nProvider locale="en" dict={en}>{children}</I18nProvider>));}
async function click(label:string,index=0){const target=[...host.querySelectorAll("button")].filter(b=>b.textContent===label)[index];expect(target,`Missing button ${label}`).toBeDefined();await act(async()=>target!.click());}
async function field(label:string,value:string){const target=[...host.querySelectorAll("label")].find(l=>l.firstChild?.textContent===label)?.querySelector("input,textarea") as HTMLInputElement|HTMLTextAreaElement;expect(target,`Missing field ${label}`).toBeTruthy();await act(async()=>{Object.getOwnPropertyDescriptor(target instanceof HTMLTextAreaElement?HTMLTextAreaElement.prototype:HTMLInputElement.prototype,"value")!.set!.call(target,value);target.dispatchEvent(new Event("input",{bubbles:true}));});}
async function submit(){await act(async()=>{host.querySelector("form")!.dispatchEvent(new Event("submit",{bubbles:true,cancelable:true}));});}
beforeEach(()=>{resetSurfaceCache();sessionStorage.clear();vi.resetAllMocks();api.confirm.mockResolvedValue(true);api.module.mockResolvedValue({module:{workspaceId:"w",state:"enabled",version:1},canManage:true});api.list.mockResolvedValue({items:[],nextCursor:null});api.lookup.mockResolvedValue([contact]);api.purposes.mockResolvedValue([]);api.plan.mockResolvedValue({record:plan});api.event.mockResolvedValue({record:event});api.ticket.mockResolvedValue({ticket});api.promotion.mockResolvedValue({promotion});api.reserve.mockResolvedValue({order:{id:"order-one"}});api.offer.mockResolvedValue({offer:{orderId:"offer-order"}});api.retryReceipt.mockResolvedValue({result:{id:"order-one"},receipt:{id:"receipt",state:"applied"}});api.createRescue.mockResolvedValue({rescue,created:true});api.settleRescue.mockResolvedValue({rescue:{...rescue,status:"settled"},created:true});api.reverseRescue.mockResolvedValue({rescue:{...rescue,status:"reversed"},created:true});api.cancelRescue.mockResolvedValue({rescue:{...rescue,status:"cancelled"},created:true});api.grant.mockResolvedValue({record:membership});api.adjust.mockResolvedValue({record:membership});api.checkIn.mockResolvedValue({});host=document.createElement("div");document.body.appendChild(host);root=createRoot(host);});
afterEach(async()=>{await act(async()=>root.unmount());host.remove();resetSurfaceCache();});
describe("[COMP:app-web/association] Catalog configuration",()=>{
  it("preserves plan fields and date precision while editing a name",async()=>{await render(<AssociationPlanForm workspaceId="w" plan={plan} disabled={false} onSaved={()=>{}}/>);await field(m.name,"New community name");await submit();expect(api.plan).toHaveBeenCalledWith("w",expect.objectContaining({key:"community",name:"New community name",benefits:["Workshops"],eligibilityNote:plan.eligibilityNote,activeFrom:plan.activeFrom,currency:"USD"}));});
  it("keeps event metadata, timezone and provider-independent catalog values",async()=>{await render(<AssociationEventForm workspaceId="w" event={event} disabled={false} onSaved={()=>{}}/>);await field(m.name,"Updated workshop");await submit();expect(api.event).toHaveBeenCalledWith("w",expect.objectContaining({slug:event.slug,title:"Updated workshop",metadata:event.metadata,timezone:event.timezone,startsAt:"2027-01-05T12:00:00.000Z",canonicalUrl:event.canonicalUrl}));});
  it("saves member-price inventory without copying derived counters into the command",async()=>{await render(<AssociationTicketForm workspaceId="w" eventId={event.id} ticket={ticket} disabled={false} onSaved={()=>{}}/>);await field(m.memberPrice,"0");await submit();const value=api.ticket.mock.calls[0][2];expect(value).toMatchObject({key:"standard",capacity:12,memberPriceMinor:0,priceMinor:0});expect(value).not.toHaveProperty("available");expect(value).not.toHaveProperty("reservedCount");});
  it("preserves a hidden promotion code on edit and sends a replacement only when entered",async()=>{await render(<AssociationPromotionForm workspaceId="w" promotion={promotion} disabled={false} onSaved={()=>{}}/>);await field(m.name,"Updated launch offer");await submit();expect(api.promotion).toHaveBeenCalledWith("w",expect.objectContaining({key:"launch",name:"Updated launch offer",percentageBasisPoints:1500,targetIds:[event.id],maxUsesPerContact:1}));expect(api.promotion.mock.calls[0][1]).not.toHaveProperty("code");await render(<AssociationPromotionForm workspaceId="w" promotion={promotion} disabled={false} onSaved={()=>{}}/>);await field(m.replacementCode,"NewSecret20");await submit();expect(api.promotion.mock.calls[1][1].code).toBe("NewSecret20");});
  it("denies direct form submission when configuration is unavailable and respects cancelled review",async()=>{await render(<AssociationPlanForm workspaceId="w" plan={plan} disabled onSaved={()=>{}}/>);await submit();expect(api.plan).not.toHaveBeenCalled();await render(<AssociationPlanForm workspaceId="w" plan={plan} disabled={false} onSaved={()=>{}}/>);api.confirm.mockResolvedValue(false);await submit();expect(api.plan).not.toHaveBeenCalled();});
  it("shows an uncertain save as failed and never schedules a retry",async()=>{api.ticket.mockRejectedValue(new Error("lost response"));await render(<AssociationTicketForm workspaceId="w" eventId={event.id} ticket={ticket} disabled={false} onSaved={()=>{}}/>);await submit();expect(host.textContent).toContain(m.failed);expect(api.ticket).toHaveBeenCalledTimes(1);});
});
describe("[COMP:app-web/association] Complimentary memberships",()=>{
  it("uses explicit dates and retains the same identity after a lost reply",async()=>{api.grant.mockRejectedValueOnce(new Error("response lost"));await render(<AssociationMembershipForm workspaceId="w" plan={plan} contact={contact} disabled={false} onSaved={()=>{}}/>);await field(m.start,"2027-02-01T10:30");await submit();expect(host.textContent).toContain(m.failed);await submit();const first=api.grant.mock.calls[0][1],second=api.grant.mock.calls[1][1];expect(second).toEqual(first);expect(first).toMatchObject({contactId:contact.id,planId:plan.id,status:"active",renewalMode:"none",endsAt:null});expect(first.idempotencyKey).toMatch(/^[a-f0-9-]{36}$/);expect(Object.values(sessionStorage)).toEqual([first.idempotencyKey]);});
  it("adjusts a stable membership without rewriting its start or minting another grant",async()=>{await render(<AssociationMembershipForm workspaceId="w" row={membership} disabled={false} onSaved={()=>{}}/>);await field(m.end,"2028-01-01T00:00");await submit();expect(api.adjust).toHaveBeenCalledWith("w",membership.id,{status:"active",endsAt:new Date("2028-01-01T00:00").toISOString(),renewalMode:"none"});expect(api.adjust.mock.calls[0][2]).not.toHaveProperty("startsAt");expect(api.grant).not.toHaveBeenCalled();});
  it("refuses complimentary grant from paid plans and manual provider-row changes",async()=>{await render(<AssociationMembershipForm workspaceId="w" plan={{...plan,feeMinor:"100"}} contact={contact} disabled={false} onSaved={()=>{}}/>);await submit();expect(api.grant).not.toHaveBeenCalled();await render(<AssociationMembershipForm workspaceId="w" row={{...membership,provider:"fake-provider"}} disabled={false} onSaved={()=>{}}/>);await submit();expect(api.adjust).not.toHaveBeenCalled();});
  it("keeps generic plan configuration available with Association disabled and displays effective access independently",async()=>{api.module.mockResolvedValue({module:{workspaceId:"w",state:"disabled",version:1},canManage:true});api.list.mockImplementation(async(_w,r)=>({items:r==="plans"?[plan]:r==="memberships"?[membership]:[],nextCursor:null}));await render(<AssociationMembershipsPanel workspaceId="w"/>);expect(host.textContent).toContain(m.ineffective);const button=[...host.querySelectorAll("button")].find(b=>b.textContent===m.newPlan)!;expect(button.disabled).toBe(false);expect(host.querySelector('a[href="/w/w/crm/contact/contact-one"]')).not.toBeNull();});
});
describe("[COMP:app-web/association] Offline payment rescue",()=>{
  it("creates a finite outstanding case with a stable request before any settlement action",async()=>{api.createRescue.mockRejectedValueOnce(new Error("response lost"));await render(<AssociationMembershipRescueForm workspaceId="w" plan={paidPlan} contact={contact} disabled={false} onSaved={()=>{}}/>);await field(m.start,"2027-01-01T00:00");await field(m.end,"2028-01-01T00:00");await field(m.paymentDue,"2026-12-01T00:00");await field(m.rescueReason,"Reviewed bank transfer exception");await submit();await submit();const first=api.createRescue.mock.calls[0][1],second=api.createRescue.mock.calls[1][1];expect(second).toEqual(first);expect(first).toMatchObject({contactId:contact.id,planId:paidPlan.id,reason:"Reviewed bank transfer exception"});expect(first.idempotencyKey).toMatch(/^[a-f0-9-]{36}$/);expect(api.settleRescue).not.toHaveBeenCalled();});
  it("reviews exact locked money and keeps settlement identity on an uncertain reply",async()=>{api.settleRescue.mockRejectedValueOnce(new Error("response lost"));await render(<AssociationMembershipRescueActionForm workspaceId="w" row={rescue} onSaved={()=>{}}/>);await field(m.evidenceReference,"bank-fixture-1");await field(m.paymentOccurred,"2026-11-30T09:00");await click(m.recordSettlement);await click(m.recordSettlement);const first=api.settleRescue.mock.calls[0][2],second=api.settleRescue.mock.calls[1][2];expect(second).toEqual(first);expect(first).toMatchObject({method:"bank_transfer",evidenceReference:"bank-fixture-1",amountMinor:10000,currency:"USD"});expect(api.confirm).toHaveBeenCalledWith(expect.objectContaining({description:expect.stringContaining("USD 10000")}));});
  it("keeps provider-bound paid plans outside the manual rescue form",async()=>{await render(<AssociationMembershipRescueForm workspaceId="w" plan={{...paidPlan,provider:"stripe",providerPlanId:"price-fixture"}} contact={contact} disabled={false} onSaved={()=>{}}/>);await field(m.start,"2027-01-01T00:00");await field(m.end,"2028-01-01T00:00");await field(m.paymentDue,"2026-12-01T00:00");await field(m.rescueReason,"Should use provider evidence");await submit();expect(api.createRescue).not.toHaveBeenCalled();});
});
describe("[COMP:app-web/association] Reservations and waitlist",()=>{
  it("reserves for a selected CRM buyer and keeps the request on retry and remount",async()=>{api.reserve.mockRejectedValueOnce(new Error("response lost"));await render(<AssociationReservationForm workspaceId="w" ticket={ticket} disabled={false}/>);await click(contact.name+contact.hint);await field(m.attendeeName,"Fictional Attendee");await field(m.attendeeEmail,"attendee@example.com");await submit();await submit();expect(api.reserve.mock.calls[1][1]).toEqual(api.reserve.mock.calls[0][1]);expect(api.reserve.mock.calls[1][1]).toMatchObject({contactId:contact.id,lines:[{ticketId:ticket.id,quantity:1,attendees:[{name:"Fictional Attendee",email:"attendee@example.com"}]}]});const id=api.reserve.mock.calls[0][1].idempotencyKey;await render(null);await render(<AssociationReservationForm workspaceId="w" ticket={ticket} disabled/>);expect(host.textContent).toContain(id);expect(Object.values(sessionStorage)).toEqual([id]);});
  it("does not reserve with no buyer or while the module is disabled",async()=>{await render(<AssociationReservationForm workspaceId="w" ticket={ticket} disabled={false}/>);await submit();expect(api.reserve).not.toHaveBeenCalled();await render(<AssociationReservationForm workspaceId="w" ticket={ticket} disabled/>);await submit();expect(api.reserve).not.toHaveBeenCalled();});
  it("keeps an uncertain promotion identity when disabled and replaces it only after explicit review",async()=>{api.offer.mockRejectedValueOnce(new Error("response lost"));await render(<AssociationWaitlistOffer workspaceId="w" row={waitlist} enabled/>);await submit();const first=api.offer.mock.calls[0][2];await render(<AssociationWaitlistOffer workspaceId="w" row={waitlist} enabled={false}/>);await submit();expect(api.offer.mock.calls[1][2]).toEqual(first);api.confirm.mockResolvedValueOnce(false);await click(m.newRequest);expect(host.textContent).toContain(first.promotionId);await click(m.newRequest);expect(host.textContent).not.toContain(first.promotionId);await submit();expect(api.offer).toHaveBeenCalledTimes(2);});
  it("cannot make a second new offer for an offered row, and shows existing order lineage",async()=>{await render(<AssociationWaitlistOffer workspaceId="w" row={{...waitlist,waitlistState:"offered"}} enabled/>);await submit();expect(api.offer).not.toHaveBeenCalled();api.list.mockResolvedValue({items:[{...waitlist,orderId:"existing-order",waitlistState:"offered"}],nextCursor:null});await render(<AssociationWaitlistPanel workspaceId="w"/>);expect(host.textContent).toContain("existing-order");expect(host.textContent).toContain(m.options.offered);});
});
describe("[COMP:app-web/association] Attendance, history and paged state",()=>{
  it("checks in by stable registration id while commerce is disabled",async()=>{api.module.mockResolvedValue({module:{workspaceId:"w",state:"disabled",version:1},canManage:true});api.list.mockImplementation(async(_w,r)=>({items:r==="events"?[event]:r==="tickets"?[ticket]:r==="registrations"?[{id:"registration-stable",attendeeName:"Fictional Attendee",attendeeEmail:"attendee@example.com",status:"confirmed",attendeeContactId:contact.id}]:[],nextCursor:null}));await render(<AssociationEventsPanel workspaceId="w"/>);const eventButton=[...host.querySelectorAll("button")].find(b=>b.textContent?.startsWith(event.title))!;await act(async()=>eventButton.click());await click(m.checkIn);expect(api.checkIn).toHaveBeenCalledExactlyOnceWith("w","registration-stable");expect([...host.querySelectorAll("button")].find(b=>b.textContent===m.newTicket)?.disabled).toBe(true);});
  it("shows the operational roster only to owners and admins, including while commerce is disabled",async()=>{api.module.mockResolvedValue({module:{workspaceId:"w",state:"disabled",version:1},canManage:true});api.list.mockImplementation(async(_w,r)=>({items:r==="events"?[event]:[],nextCursor:null}));await render(<AssociationEventsPanel workspaceId="w"/>);await act(async()=>[...host.querySelectorAll("button")].find(b=>b.textContent?.startsWith(event.title))!.click());expect(host.textContent).toContain(m.operationalRosterHelp);expect([...host.querySelectorAll("button")].some(b=>b.textContent===m.operationalRoster)).toBe(true);await render(null);resetSurfaceCache();api.module.mockResolvedValue({module:{workspaceId:"w",state:"enabled",version:1},canManage:false});await render(<AssociationEventsPanel workspaceId="w"/>);await act(async()=>[...host.querySelectorAll("button")].find(b=>b.textContent?.startsWith(event.title))!.click());expect(host.textContent).not.toContain(m.operationalRosterHelp);});
  it("requires and reviews a reason before an owner corrects a stable check-in",async()=>{api.list.mockImplementation(async(_w,r)=>({items:r==="events"?[event]:r==="registrations"?[{id:"registration-stable",attendeeName:"Fictional Attendee",attendeeEmail:"attendee@example.com",status:"checked_in",attendeeContactId:contact.id}]:[],nextCursor:null}));api.correctCheckIn.mockResolvedValue({registration:{id:"registration-stable",status:"confirmed"}});await render(<AssociationEventsPanel workspaceId="w"/>);await act(async()=>[...host.querySelectorAll("button")].find(b=>b.textContent?.startsWith(event.title))!.click());const button=[...host.querySelectorAll("button")].find(b=>b.textContent===m.correctCheckIn) as HTMLButtonElement;expect(button.disabled).toBe(true);await field(`${m.correctionReason}: Fictional Attendee`,"Scanned the wrong badge");await click(m.correctCheckIn);expect(api.confirm).toHaveBeenCalledWith(expect.objectContaining({description:expect.stringContaining("Scanned the wrong badge")}));expect(api.correctCheckIn).toHaveBeenCalledWith("w","registration-stable","checked_in","Scanned the wrong badge");});
  it("lets an owner retry frozen provider evidence and follows audit/delivery continuations",async()=>{api.list.mockImplementation(async(_w,r,q)=>({items:r==="receipts"?[{id:"receipt",provider:"fake-provider",eventId:"event-evidence",state:"needs_reconciliation",attempts:2,errorCode:"invalid_transition"}]:r==="audit"?[{id:q.cursor?"audit-last":"audit-first",action:"order.created",actorKind:"user"}]:[{id:"delivery",eventType:"association.order.paid",status:"failed",attempts:2,occurredAt:"2027-01-01"}],nextCursor:r==="audit"&&!q.cursor?"audit-next":null}));await render(<AssociationOperationsPanel workspaceId="w"/>);expect(host.textContent).toContain(m.options.needs_reconciliation);expect(host.textContent).toContain("invalid_transition");await click(m.retryReceipt);expect(api.confirm).toHaveBeenCalledWith(expect.objectContaining({description:m.retryReceiptHelp}));expect(api.retryReceipt).toHaveBeenCalledWith("w","receipt");await click(t.next);expect(api.list).toHaveBeenCalledWith("w","audit",expect.objectContaining({cursor:"audit-next"}));expect(host.textContent).toContain("audit-last");});
  it("keeps receipt resolution unavailable to ordinary members",async()=>{api.module.mockResolvedValue({module:{workspaceId:"w",state:"enabled",version:1},canManage:false});api.list.mockImplementation(async(_w,r)=>({items:r==="receipts"?[{id:"receipt",provider:"fake-provider",eventId:"event-evidence",state:"needs_reconciliation",attempts:1,errorCode:"conflict"}]:[],nextCursor:null}));await render(<AssociationOperationsPanel workspaceId="w"/>);expect(host.textContent).toContain(m.options.needs_reconciliation);expect([...host.querySelectorAll("button")].some(button=>button.textContent===m.retryReceipt)).toBe(false);});
  it("retains last-good rows when refresh fails, reacts to stale marks and resets cursors on filter changes",async()=>{
    function List({eventId}:{eventId:string}){const page=useAssociationPage("w","registrations",{eventId});return <AssociationListState {...page}>{page.data?.items.map(row=><p key={row.id}>{row.id}</p>)}</AssociationListState>;}
    api.list.mockImplementation(async(_w,_r,q)=>({items:[{id:q.cursor?"second":"first"}],nextCursor:q.cursor?null:"next"}));await render(<List eventId="one"/>);await click(t.next);expect(host.textContent).toContain("second");api.list.mockRejectedValue(new Error("offline"));await act(async()=>markSurfaceCacheStale("crm:w:"));expect(host.textContent).toContain("second");expect(host.textContent).toContain(m.loadFailed);api.list.mockResolvedValue({items:[{id:"new-event"}],nextCursor:null});await render(<List eventId="two"/>);expect(api.list).toHaveBeenLastCalledWith("w","registrations",{eventId:"two",cursor:undefined});expect(host.textContent).toContain("new-event");
  });
});
